### ISSUE TITLE
got  "message": "Some error occurred."     } }

### ISSUE THREAD

**Issue by Ashishrisetech** [aaabhilash97/aadhaar-paperless-offline-ekyc-apis#2]
below is error given when verify otp
----------------------------------------------------
{"level":"error","ts":"2022-11-30T15:56:14.103+0530","caller":"v1/aadhaar_apis.go:158","msg":"VerifyOtpAndGetAadhaar","aadhaarapi.IsRedownloadError(err)":false,"aadhaarapi.IsSessionExpired(err)":false,"req":"session_id:\"42dd11bef78d1513c077260e7f7ad032\"  otp:\"456435\"  zip_code:\"2345\"","error":"Unknown error"}
Unknown error

can i know how to resolve the issue when download zip file.

**Comment by aaabhilash97** [comment]
Old aadhaar website(https://resident.uidai.gov.in/offline-kyc ) trying scrap in this project deprecated.
